name: Package and Release

on:
  push:
    branches:
      - main

jobs:
  release-tag:
    permissions:
      # create tag
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.ccv.outputs.new-tag }}
      new-tag-version: ${{ steps.ccv.outputs.new-tag-version }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - name: Bump tag if necessary
      id: ccv
      uses: smlx/ccv@d3de774e9b607b079940a7a86952f44643743336 # v0.9.0
      
  releasae-build:
    runs-on: ubuntu-latest
    needs: release-tag
    if: needs.release-tag.outputs.new-tag == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tarball
        run: tar -czvf init.tar ./src

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: init-tarball
          path: init.tar

  release-publish:
    needs: [releasae-build, release-tag]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: prod
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: init-tarball
          path: .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.release-tag.outputs.new-tag-version}}
          release_name: Release ${{needs.release-tag.outputs.new-tag-version}}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./init.tar
          asset_name: init.tar
          asset_content_type: application/x-tar